theme: jekyll-theme-minimal
title: [Peng Liu]
logo: ["jenniferliumao/jenniferliumao.github.io/WechatIMG143.jpeg"]
description: [MS student in Data Science at University of San Francisco]
email: pliu25@usfca.edu
