remote_theme: artemsheludko/flexible-jekyll
title: Peng Liu
description: > # this means to ignore newlines until "baseurl:"
  Master's student in Data Science with working experience in mechanical engineering and materials science. Passionate about combining data insights with domain knowledge in real-world applications. 

url: "jenniferliumao.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Peng Liu # add your name
author-img: images/mylogo.png # add your photo
about-author: Master's student in Data Science with working experience in mechanical engineering and materials science. Passionate about combining data insights with domain knowledge in real-world applications. 

social-github: jenniferliumao # ig handle
social-linkedin: Peng Liu # add your Linkedin handle
social-email: pliu25@usfca.edu # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
