theme: jekyll-theme-minimal
title: Peng Liu
logo: /images/mylogo.png
description: [Master's student in Data Science with working experience in mechanical engineering and materials science. 
Passionate about combining data insights with domain knowledge in real-world applications.]
